export const sourcingCopy = {
  en: {
    find: "Find a part",
    description:
      "Search OEM numbers, manufacturer SKUs and names. Catalog rows remain unreviewed until evidence resolves the vehicle and equipment.",
    unknown: "Unknown / not verified",
    query: "Number or name",
    system: "System",
    status: "Fitment status",
    position: "Position",
    configuration: "Configuration",
    all: "All, including unknowns",
    owner: "Owner candidates",
    variants: "Original catalog variants",
    front: "Front",
    rear: "Rear",
    exact: "Exact number",
    related: "Related number; relationship needs review",
    name: "Catalog / name match",
    candidate: "Candidate",
    rejected: "Rejected for this setup",
    unreviewed: "Unreviewed catalog entry",
    confirmed: "Confirmed for specified configuration",
    conflicting: "Conflicting evidence",
    facts: "Vehicle facts and unknowns",
    evidence: "Evidence and contradictions",
    checks: "Unresolved checks",
    quantity: "Quantity and order unit",
    dimensions: "Dimensions (original units)",
    relations: "Directed relationships",
    offers: "Dated supplier leads",
    brief: "Supplier brief",
    sources: "Source catalog restrictions",
    coverage: "Review coverage",
    version: "Record version",
    review: "Review required",
    fitment:
      "Catalog inclusion does not confirm fitment. Verify exact equipment, production date and part interfaces.",
    manual: "PDF applicability and reviewed pages",
    procedure:
      "Inherited procedure: specifications and steps require exact-page and configuration review. Intervals are owner recommendations until verified against the factory schedule.",
    copy: "Copy supplier brief",
    copied: "Copied",
    diagrams: "Original diagrams",
    total: "Total catalog rows",
    reviewed: "Reviewed claims",
    fits: "Confirmed fits",
  },
  vi: {
    find: "Tìm phụ tùng",
    description:
      "Tìm mã OEM, mã nhà sản xuất và tên. Dòng catalogue chưa xác minh cho đến khi chứng cứ khớp xe và trang bị.",
    unknown: "Chưa biết / chưa xác minh",
    query: "Mã hoặc tên",
    system: "Hệ thống",
    status: "Trạng thái tương thích",
    position: "Vị trí",
    configuration: "Cấu hình",
    all: "Tất cả, gồm mục chưa biết",
    owner: "Ứng viên cho xe chủ sở hữu",
    variants: "Biến thể catalogue gốc",
    front: "Trước",
    rear: "Sau",
    exact: "Khớp mã chính xác",
    related: "Mã liên quan; cần xác minh quan hệ",
    name: "Khớp catalogue / tên",
    candidate: "Ứng viên",
    rejected: "Không phù hợp cấu hình này",
    unreviewed: "Dòng catalogue chưa xác minh",
    confirmed: "Đã xác minh cho cấu hình cụ thể",
    conflicting: "Chứng cứ mâu thuẫn",
    facts: "Thông tin xe và mục chưa biết",
    evidence: "Chứng cứ và mâu thuẫn",
    checks: "Kiểm tra còn thiếu",
    quantity: "Số lượng và đơn vị đặt hàng",
    dimensions: "Kích thước (đơn vị gốc)",
    relations: "Quan hệ có chiều",
    offers: "Nguồn cung có ngày kiểm tra",
    brief: "Thông tin gửi nhà cung cấp",
    sources: "Điều kiện catalogue nguồn",
    coverage: "Phạm vi xác minh",
    version: "Phiên bản dữ liệu",
    review: "Cần xác minh",
    fitment:
      "Có trong catalogue không chứng minh phù hợp. Kiểm tra trang bị, ngày sản xuất và giao diện phụ tùng.",
    manual: "Điều kiện áp dụng PDF và trang đã kiểm tra",
    procedure:
      "Quy trình cũ: cần đối chiếu trang nguồn và cấu hình cho thông số và bước làm. Chu kỳ là khuyến nghị chủ xe cho đến khi xác minh lịch hãng.",
    copy: "Sao chép thông tin nhà cung cấp",
    copied: "Đã sao chép",
    diagrams: "Sơ đồ gốc",
    total: "Tổng dòng catalogue",
    reviewed: "Nhận định đã kiểm tra",
    fits: "Phù hợp đã xác minh",
  },
} as const;
