import type { Locale } from "./locale";
const labels: Record<string, [string, string]> = {
  build_from: ["Build from", "Sản xuất từ"],
  build_to: ["Build through", "Sản xuất đến"],
  braking_system: ["Brake system", "Hệ phanh"],
  production_period: ["Production period", "Giai đoạn sản xuất"],
  applies_for_models: ["Original model restrictions", "Điều kiện model gốc"],
  notes: ["Original notes", "Ghi chú gốc"],
  diameter: ["Diameter", "Đường kính"],
  disc_thickness: ["Disc thickness", "Độ dày đĩa"],
  height: ["Height", "Chiều cao"],
  centering: ["Center bore", "Lỗ tâm"],
  minimum_disc_thickness: ["Minimum disc thickness", "Độ dày đĩa tối thiểu"],
  holes: ["Hole count", "Số lỗ"],
  pad_width: ["Pad width", "Chiều rộng má"],
  pad_height: ["Pad height", "Chiều cao má"],
  total_pad_thickness: ["Total pad thickness", "Độ dày toàn bộ má"],
  nominal_diameter: ["Nominal diameter", "Đường kính danh nghĩa"],
  width: ["Width", "Chiều rộng"],
  maximum_diameter: ["Maximum diameter", "Đường kính tối đa"],
  model_year: ["Model year", "Năm model"],
  build_date: ["Build date", "Ngày sản xuất"],
  chassis: ["Chassis code", "Mã khung"],
  applied_model: ["Applied-model code", "Mã model đầy đủ"],
  market: ["Market", "Thị trường"],
  steering: ["Steering", "Tay lái"],
  engine: ["Engine", "Động cơ"],
  transmission: ["Transmission", "Hộp số"],
  transmission_code: ["Transmission code", "Mã hộp số"],
  drivetrain: ["Drivetrain", "Hệ truyền động"],
  body: ["Body", "Thân xe"],
  trim: ["Trim", "Phiên bản"],
  abs: ["ABS", "ABS"],
  catalyst: ["Catalyst", "Bộ xúc tác"],
  front_brakes: ["Front brakes", "Phanh trước"],
  rear_brakes: ["Rear brakes", "Phanh sau"],
  modifications: ["Modifications", "Thay đổi"],
  power_rating: ["Power rating", "Công suất"],
  oem_supersession: ["OEM supersession", "Mã OEM thay thế có chiều"],
  aftermarket_cross_reference: [
    "Aftermarket cross-reference",
    "Mã đối chiếu hãng khác",
  ],
};
export function sourcingField(key: string, locale: Locale): string {
  return labels[key]?.[locale === "vi" ? 1 : 0] ?? key.replaceAll("_", " ");
}
